version: '3'

services:
  mysql: 
    image: mysql:5.7
    container_name : mysql
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
